# Generated by Django 4.2.2 on 2023-07-05 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=15)),
                ('adres', models.CharField(max_length=255)),
                ('notlar', models.TextField()),
                ('urun', models.TextField()),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Yemek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icerik', models.TextField()),
                ('kategori', models.CharField(choices=[('corba', 'Çorbalar'), ('ana_yemek', 'Ana Yemekler'), ('tatli', 'Tatlılar')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SiparisUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField()),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yemekler.siparis')),
                ('yemek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yemekler.yemek')),
            ],
        ),
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField()),
                ('tutar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yemek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yemekler.yemek')),
            ],
        ),
    ]
